apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io
spec:
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                webhookOptions:
                  default:
                    - name: nodedebuggingpodmetada.spo.io
                      objectSelector:
                        matchLabels:
                          debug.openshift.io/managed-by: "oc-debug"