apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io
spec:
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                webhookOptions:
                  - name: nodedebuggingpodmetada.spo.io
                    objectSelector:
                      matchLabels: # Use matchLabels for exact matching
                        debug.openshift.io/managed-by: "oc-debug"
